= Devoxx France 2022
Damien Cuenot <icon:github[] https://github.com/dcuenot/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/cdams86[@cdams86]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 2
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

== MERCREDI

=== Présentation du salon

* https://www.devoxx.fr/, du 20 au 22/04/2022
* Et c'est parti pour Devoxx France 2022, *les "vrais" 10 ans de Devoxx France* ! 😁😁😁
* Template inspiré par https://twitter.com/thomasschwender[@thomasschwender], merci à lui!
* Doc AsiiDoctor: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

=== Comprendre GraphQL

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/geoffroy_couprie[Geoffroy Couprie] et https://cfp.devoxx.fr/2022/speaker/guillaume_scheibel[Guillaume Scheibel]
--
GraphQL est une spécification décrivant un language de requêtes pour API sur une base d'un contrat fortement typé. En plus du contrat, GraphQL se base sur une sélection explicite des champs permettant un requêtage riche évitant soit "l'overfetching" (recevoir des données inutiles) ou la multiplications des requêtes.

GraphQL est aussi connu pour son écosystème clients (web et mobiles) ou serveur avec la possibilité d'écrire des services dans une multitude de langages. Durant cette session, nous verrons comment développer un schéma GraphQL avec différents languages (tel que typescript, kotlin voir rust). Nous aborderons entre autres:
- Le système de types en GraphQL: objet, types polymorphiques, queries (lectures), mutations (écritures), subscriptions (streaming)
- La gestion des erreurs
- Strategies de résolutions des requêtes (avec par exemples les coroutines)
- Technique plus avancées (context de requêtes, chaines d'interceptions etc).
--

==== Notes

Bare minimal query
```
schema {
    query {}
}
```

Dans une query, on ajoute un ! pour signaler qu'un champ est obligatoire, et ne doit pas être null, permet de gérer des modes dégradés.

La https://spec.graphql.org/June2018/[spécification GraphQL] est la bible
Github utilise GraphQL, voici https://docs.github.com/en/graphql/overview/explorer[la doc]

L'objectif de GraphQL est de limiter la data qui transite sur le réseau, c'est le client qui défini les champs à récupérer, l'ordre d'affichage...

Si un champs est associé à une fonction côté serveur, s'il n'est pas requêté par le client, la fonction ne sera pas appelée, ce qui permet de fortement optimiser les temps de réponse si la fonction fait une recherche en BDD par ex.

En GraphQL, il y a 3 types de requêtes différents:
- `Query`: Requête de lecture
- `Mutation`: Requête de mise à jour. Si plusieurs mutations sont demandées dans la même query, elles sont exécutées séquentiellement
- `Subscription`: Streaming

En GraphQL tout est en POST, et les réponses sont en 200 ou 500. 500 quand la query n'est pas valable, et si c'est une error métier, on reçoit un 200 et dans le body de réponse le bloc `error` est non vide.

https://www.apollographql.com[Apollo] propose différents outils pour explorer, stitcher des graphs: Rover, Studio, explorer

=== Zero Trust : the new normal !

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/laurent_grangeau[Laurent Grangeau] et https://cfp.devoxx.fr/2022/speaker/tony_jarriault[Tony Jarriault]
--
Avec l'arrivée du COVID, les entreprises ont dû accélérer l'adoption du télétravail et ont vu l'augmentation du nombre de partenaires externes avec l'ouverture de son SI, ce qui nécessite de revoir la sécurité périmétrique des infrastructures. La démarche Zero Trust consiste à réduire la « confiance implicite » accordée aux utilisateurs et aux activités menées par le biais des équipements du SI. Pour garantir cette confiance, les entreprises ont pris le parti de se baser sur l'identité des utilisateurs pour vérifier et les authentifier sur l'ensemble des ressources accessibles. Dans cette session, nous ferons un bref rappel de ce qu'est la sécurité périmétrique (VPN, firewall, zoning réseau, …). Nous présenterons ensuite les grands principes du Zero Trust tel que le least privilege access, la microsegmentation réseau, l'authentification multi-facteur, etc. Nous comparerons aussi la sécurité périmétrique (modèle du château fort) avec celle de l'approche Zero Trust (modèle de l'aéroport) ; et nous reviendrons sur les différents modèles d'autorisation (MAC, RBAC, ABAC). Enfin, nous montrerons des exemples d'implémentation Zero Trust à travers des produits comme Boundary d'Hashicorp.
--

==== Notes

===== Why?
Télétravail, cloud, augmentation de la surface d'attaque. Propice aux ransomwares, et attaques.
BYOD n'est pas une pratique à recommander

90% des brèches sont de mauvaises configurations
Des clusters K8S de Tesla étaient mal configurés et ont permis de miner du Bitcoin
https://cybermap.kaspersky.com

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-207.pdf[NIST Zero Trust Architecture 800-207]

==== Trust no one, verify everything
* Identity
* Perimeter
* Network
* Application
* Data
* Observability

https://orangecyberdefense.com/fr/insights/blog/detection/soc-siem-xdr-mdr-edr-quelles-differences/[SIEM, XDR]

_La confiance n'exclut pas le contrôle_ - Lénine


==== Architecture
* Contrôler l'identité
    - MFA
    - Qui je suis
    - Ce que je sais
    - Ce que je possède

* Contrôler les devices
    - MDM
    - Forcer à avoir des devices à jour

Défense périmétrique ne suffit clairement plus. https://www.clever-cloud.com/blog/guests/2015/06/16/the-end-of-the-fortress-metaphor/[The End of the Fortress Metaphor]

==== Model d'authorisation
* ACL (Access Control List) une personne peut agir sur un object
* DAC (Discretionary Access Control) une personne peut agir sur un objet et peut donner cette permission à d'autres
* MAC (Mandatory Access Control) - SELinux - une personne peut agir sur un object, et l'object peut vérifier qu'une personne peut agir sur lui
* RBAC (Role Based Access Control) - une personne à un rôle, et par rapport à ce rôle on définit les permissions sur un object
* ABAC (Attribute Based Access Control) - XACML - une personne peut accéder à un attribut dans un environnement (un contexte)

===== Modèle aéroport
Modèle de sécurité avec des zones public, privée, duty free, tarmac... qui est bien plus clair que le modèle chateau fort.

==== Principes de Zero Trust
1. All data sources and compute services are considered resources
2. Toutes les communications sont sécurisées, quelques soient l'endroit sur le réseau
3. Les accès individuels sont granted par une session (avec un TTL)
4. L'accès aux ressources est déterminé par des politiques dynamiques
5. Monitore et mesure l'intégrité et la sécurité de tous les assets
6. authent et authorization doivent être validée avant de donner accès à une donnée
7. Collecte d'un maximum d'info sur le réseau, les assets, pour détecter des failles

==== Demo Harshicorp
https://www.boundaryproject.io[Boundary]
Semble fonctionner comme un bastion, mais qui gère authentification + autorisation, et de plus boundary génère à la volée des clés pour accéder au VM du subnet private, fonctionne aussi pour un accès BDD PostgreSQL. Les crédentials temporaires sont stockés dans un Vault.
Comme les users sont créés à la volée, il faut faire de la corrélation entre la trace dans la BDD et les logs d'accès Boundary.

Boundary est pour du Human 2 Machine. Si besoin de faire du Machine 2 Machine, il faut plutôt faire un Consul avec un Vault.

==== https://www.beyondcorp.com[BeyondCorp Enterprise]
* N'importe quel googlers peut se connecter depuis n'importe quel réseaux *sans passer par un VPN*


==== Takeaways
* Sécu périmétrique n'est plus une option
* Zero trust framework basé sur device, identité, automation pour protéger les data, et bien sur le reseau
* Des solutions existent déjà (boundary, beyondcorp)

=== Pourquoi vous n'attirerez et ne retiendrez pas les femmes dans vos équipes tech !

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/marcy_ericka_charollois[Marcy Ericka Charollois]
--
Les femmes sont sous-représentées dans le domaine du numérique. Elles représentent à ce jour uniquement 30% des salariés, tous métiers confondus.

Que s´est-il passé dans ce secteur professionnel pourtant dominé par la gente feminine lors de sa génèse ? Les femmes ne se sentiraient-elles plus ou pas à leurs places ?

Pourtant, les femmes communiquent. Hélas, bien souvent, on ne les écoute pas. Résultat ? Migration vers des métiers corollaires, brown-out, désincarnation dans l'équipe, démission, création de la FemTech et de safe places comme lieux d'expression communautaire.

Alors, si vous voulez favoriser la mixité et que vous avez saisi que la cause des femmes dans la tech est une brèche pour résoudre, en plus, la problématique de la diversité et de l'inclusion, venez découvrir comment améliorer vos pratiques !
--

==== Notes
Groupe majoritaire - Biais de confirmation - biais de sympathie
--> ceci induit un statu quo

Avec une logique du groupe majoritaire, il y a 2 dynamique possible: le groupe inclu, ou exclu
Attitude face au changement:
* 15% de refractaire
* 70% de neutre
* 15% de partants

https://www.ipsos.com/sites/default/files/ct/publication/documents/2022-02/women-in-tech-survey-2021-infographic-ipsos.pdf[What is holding back women in tech ?] by Ipsos
https://www.ipsos.com/sites/default/files/ct/publication/documents/2022-02/women-in-tech-survey-2021-ipsos.pdf[version longue]

90% des compétences pour postuler alors que les hommes estiment que 60% est suffisant
Attention au titre de postes (dévelopeuse)
Transparence salariale
Moments conviavilatés inclusif, pas s'arrêter à la "bro culture"

Encouragez à prendre la parole, à être des roles modèles.
La diversité et inclusion est un élément indispensable, augmente la productivité et la satisfaction globale


=== 17h45 - 18h15 : Bien maîtriser les Dev Tools de vos navigateurs

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/romain_linsolas[Romain Linsolas]
----
Développer avec efficacité, c'est non seulement choisir les bons outils, mais surtout bien savoir les utiliser. Pour le développement web, si l'éditeur reste l'outil principal, le navigateur est lui aussi un élément primordial.

La grande majorité des développeurs et développeuses web est familière avec les fonctionnalités de base des Dev Tools intégrés aux navigateurs. Pourtant dans les faits, il s'avère que beaucoup d'entre eux n'utilisent qu'une petite partie de leurs capacités, et même ignorent bon nombre des fonctionnalités offertes par ces outils.

Dans ce Tools In Action, au travers de différentes démonstrations, nous allons voir les possibilités avancées offertes par ces outils : comment détecter et analyser les problèmes de performances, comment simuler d'autres environnements ou contextes (latences réseaux, problèmes d'accessibilité, etc.) ou encore découvrir des fonctions très intéressantes pour améliorer ses développements.

Nous nous focaliserons en grande partie sur les Dev Tools de Chrome, mais nous évoquerons aussi les différences avec ceux des principaux navigateurs concurrents.
----

==== Notes

TO BE COMPLETED

=== 18h30 - 19h00 Github Co-Pilot : Addictif ou Efficace ?

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/johan_jublanc[Johan Jublanc] et https://cfp.devoxx.fr/2022/speaker/simon_provost[Simon Provost]
----
Au cours de cette conversation, nous partagerons notre retour d'expérience sur l'utilisation d'un outil de pair programming intelligent (AI pair programmer) : GitHub Copilot. Nous examinerons comment l'utiliser, les avantages qu'il procure et les limites que nous avons identifiées. Nous tenterons ainsi de donner des éléments pour déterminer si ce plugin tient bien la promesse d'aider les développeurs à écrire du code plus rapidement et avec moins de travail.

Nous commencerons par une micro-session de "live-coding" en direct pour suivre les suggestions en temps réel et comparer ce qui est proposé d'un utilisateur à l'autre. Nous verrons ensuite les points forts et les questions qui se posent lors de l'utilisation de l'outil. Enfin, nous terminerons par une courte discussion sur comment GitHub Copilot fait évoluer la manière dont les développeurs documentent leur code.
----

==== Notes

TO BE COMPLETED

== JEUDI

=== 09h00 - 09h20 : La Keynote de Devoxx France 2022 - 10 ans déjà

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/nicolas_martignole[Nicolas Martignole], https://cfp.devoxx.fr/2022/speaker/antonio_goncalves[Antonio Goncalves], https://cfp.devoxx.fr/2022/speaker/zouheir_cadi[Zouheir Cadi]

--
Devoxx France a été créé en 2012, après 4 années d'aventure avec le Paris JUG. C'est le moment de venir partager avec nous quelques souvenirs, de revenir sur ces 10 dernières années.
--

==== Notes

TO BE COMPLETED

=== 09h25 - 09h45 : 10 ans de Tech à travers le podcast Niptech

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/benoit_curdy[Benoit Curdy], https://cfp.devoxx.fr/2022/speaker/michael_monney[Michael Monney], https://cfp.devoxx.fr/2022/speaker/baptiste_freydt[Baptiste Freydt]

--
Une keynote pour passer en revue les innovations qui ont secoué la tech depuis la naissance de Devoxx FR il y a dix ans. À travers les expériences du podcast Niptech et de sa communauté, nous partagerons des leçons apprises à la dure dans le but de nous aider à préparer ces dix prochaines années.
--

==== Notes

TO BE COMPLETED

=== 09h50 - 10h10 (AB) : Slow.tech : il est urgent de hacker le système !

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/frederic_bordage[Frédéric Bordage]
--
Selon le GIEC, il nous reste 3 ans pour léguer un monde « vivable » à nos enfants. Sacré challenge ! Alors comment agir vite et fort dans notre univers numérique ? Une seule solution : sortir du cadre et hacker le système. C'est que propose la démarche slow.tech. En associant low et high tech, elle permet de diviser par un facteur 4 à 10 nos impacts numériques. De l'usage ingénieux d'un smartphone pour remplacer un cabinet d'ophtalmologie en passant par l'association d'un chien et d'une IA pour détecter un cancer, les écoconcepteurs de la slow.tech détournent les codes et les patterns habituels pour faire mieux avec moins. Prêt.e à emprunter cette « voie du milieu » ? Le hacker qui est en toi doit se réveiller !
--

=== 10h45 - 11h30 : Comprendre les enjeux de consommation de ressource et d'énergie dans le secteur numérique

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/quentin_adam[Quentin Adam], https://cfp.devoxx.fr/2022/speaker/pierre_beyssac[Pierre Beyssac]
--
L'enjeu de la transition écologique de toutes les activités humaine est également appelé à se généraliser au numérique, et comme les outils informatiques sont symbole de la modernité, une exigence d'exemplarité leur sont souvent demandée, voire même imposée par le biais de rapports “RSE” (obligatoire dans certaines conditions) par exemple. Il appartient donc aujourd'hui de se doter d'outils de réflexion et de compréhension des impacts de nos activités, et une rapide présentation des forces en présence et mécanismes menant à la législation environnementale.

Dans cet exposé, les orateurs vont d'abord présenter le cadre général de consommation de ressources, définir quelles ressources et à quel moment du cycle de vie. Ensuite seront étudiées les différentes phases de consommations, l'importance des variations de mesure, de pilotage des consommation, les différentes conceptions, et les impacts provoqués par le code ou la consommation réseau.

L'objectif de la présentation est de ressortir avec un panorama clair des enjeux et impacts de la chaîne de production IT, les différents niveaux d'actions possibles en fonction de son poste, les bonnes pratiques possibles à étudier pour son or
--

==== Notes

TO BE COMPLETED

=== 11h45 - 12h30 : Model-Driven Design

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/bruno_boucard[Bruno Boucard]
--
Si le Domain-Driven Design était une fleur, le Model-Driven Design en serait le nectar. Je vous propose de faire une plongée au cœur de la modélisation DDD, appelée Model-Driven Design. Afin de comprendre comment obtenir un modèle juste, expressif et frugal, nous visiterons l'essentiel des ateliers qui contribue à nourrir les modèles mentaux associés au domaine métier :
- Event Storming,
- Example Mapping,
- CRC Cards,
- Story Mapping.

Avant de rentrer dans le cœur du sujet, je rappellerai l'origine du DDD selon Eric Evans: Bounded Context et les corollaires associés. Une fois planté le décor, nous pourrons expliquer le Model-Driven Design qui se décompose en deux :

Le Supple Design : une suite de patterns au service d'un code souple et fiable.

Le Deep Model : processus de modélisation du problème métier par raffinement successif. Les plus chanceux auront peut-être un Breakthrough.

Je conclurais par le Whirlpool Process of Model Exploration proposé par Eric Evans

Après cette conférence, vous ne verrez plus le Domain-Driven Design tout à fait de la même façon.
--

==== Notes

TO BE COMPLETED

=== 13h00 - 13h15 : Equity for software engineers

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/damien_pacaud[Damien Pacaud]
--
De plus en plus d entreprises proposent, en complément de la rémunération, des « packages d'équity ».
C'est un cercle vertueux qui démarre en Europe et il peut être utile de prendre ces éléments en compte lorsque vous cherchez votre nouvel emploi.
Bien souvent, les développeurs en France considèrent peu ces éléments de rémunération et n'y prêtent pas beaucoup d'attention.

Ce talk a pour but de démystifier le monde bizarre des BSPCE, AGA, RSU, Warrants et autres Stock options.
--

==== Notes

TO BE COMPLETED


=== 13h30 - 14h15 : Protéger son organisation des attaques par le système de build

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/louis_jacomet[Louis Jacomet]
--
Tous les jours, les développeurs assemblent du code des dizaines de fois. Parfois de façon transparente dans l'IDE, explicitement en ligne de commande ou sur l'environnement de CI. Lors de ces actions, la notion de sécurité est souvent reléguée au second plan voire simplement ignorée.

Cette présentation illustrera les vecteurs d'attaque et expliquera comment les mitiger. L'outil de build est par définition à risque car il s'agit d'un environnement d'exécution. Certaines pratiques permettent heureusement de réduire significativement ces risques:
- S'assurer que les dépendances sont celles attendues
- Rejeter les dépendances vulnérables (Log4j??)
- Avoir un build reproductible
- Utiliser un environnement éphémère
- Valider les contributions externes

Nous illustrerons ces points avec Gradle mais la plupart des recommandations sont valables pour Apache Maven aussi.
--

==== Notes

TO BE COMPLETED

=== 14h30 - 15h15 (252AB) : Vers une culture où tout le monde est responsable de l'indisponibilité

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/emmanuel_bernard[Emmanuel Bernard]
--
Nous sommes des développeurs applicatifs. Mais c'est loin d'un service en prod. Et de nos jours entre le devops, l'openapi, la constitution d'un SI construit sur des APIs, on est tous responsable d'un service.
Je vous propose une rétrospective de la transition chez un éditeur d'une équipe de dev produit en une équipe de service cloud faisant tourner des milliers d'instances pour d'autres, les expériences acquises et de tout ce que l'on a dû (dés)apprendre en chemin.

C'est pas tant le cœur du code qui change, plutôt la culture de l'équipe, la conception des systèmes qui entourent et supportent ce code en prod. Quel impact sur l'architecture ? Comment construire des Standard Operating Procédures ? Comment on pense un SLA ? Comment penser blast radius, voisins bruyants, SRE ? Comment penser le risque ? Etc.

Après cette présentation, vous aurez des clés pour penser la transformation de vos équipes en un modèle où tout le monde est responsable du SLO (Service Level Objective) dont l'indisponibilité fait partie.
--

==== Notes

TO BE COMPLETED

=== 15h30 - 16h15 : Coder pour l'Éternité, comprendre le développement sur la blockchain Ethereum

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/mathias_herberts[Mathias Herberts]
--
La blockchain est de toutes les discussions, mais trop souvent on assimile blockchain et cryptomonnaies. Quel que soit l'avis que l'on peut avoir sur la question, il ne faut pas oublier que la blockchain c'est avant tout du code qui s'exécute dans un environnement très particulier. Cette présentation vise à plonger dans les profondeurs de la blockchain Ethereum en couvrant des sujets comme la machine virtuelle sous-jacente, le rôle des mineurs, les contrats intelligents et leur modèle d'exécution, les oracles. Vous sortirez de là en ayant une compréhension de la blockchain Ethereum du point de vue du code et avec un peu de chance l'envie de laisser une trace pour la postérité en déployant votre propre code sur cette blockchain.
--

==== Notes

TO BE COMPLETED

=== 16h45 - 17h30 : S'affranchir de la Pyramide des Tests

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/jonathan_boccara[Jonathan Boccara]
--
Tester son code c'est facile à dire, mais écrire des tests utiles dans du code en entreprise, c'est pas toujours facile à faire.

En théorie les tests doivent nous aider, pourtant: - Le code ne se prête pas toujours aux tests unitaires, - On se retrouve parfois à refactorer les tests quand on refactore le code, - La pyramide des tests est souvent inversée, - Certains tests sont toujours verts, sauf quand ils sont rouges pour de mauvaises raisons, - On a beau tester le code, on a toujours des bugs, - Etc.
La meilleure façon d'éviter ces problèmes est d'avoir les clefs pour choisir le bon test à écrire (ou à ne pas écrire!) en fonction du code à tester.
Le but de cette présentation est de vous rendre autonome sur votre stratégie de tests, en vous présentant les tenants et aboutissants des différents types de test et du testing en général.
En particulier vous verrez: - pourquoi la pyramide des tests est contre-productive - quand écrire des tests unitaires et quand ne surtout pas en écrire, - comment rédiger des tests robustes et clairs - les différentes abstractions que l'on peut tester
--

==== Notes

TO BE COMPLETED

=== 17h45 - 18h15 : Git, back to the future

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/antoine_ceol[Antoine Ceol]
--
Tout le monde utilise Git (où presque) et tout le monde s'est déjà retrouvé dans un état WTF 😱🤬🤯.

On va prendre ensemble un peu moins de 30 minutes pour apprendre à se dépatouiller quand on veut revenir en arrière, améliorer, et pourquoi pas, effacer son historique. Ça peut-être dangereux, mais, connaissant les avantages et anticipant les risques, ca en vaut la peine. L'approche se fera par l'exemple en ligne de commande ⌨️, un (git) bash suffit, pas besoin de DeLorean
--

==== Notes

TO BE COMPLETED

=== 18h30 - 19h00 : Jouer à Minecraft avec une IA générée par GPT-3

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/wassim_chegham[Wassim Chegham] et https://cfp.devoxx.fr/2022/speaker/tiffany_souterre[Tiffany_souterre]
--
Il y a des joueurs qui jouent à Minecraft pour le plaisir de jouer, d'autres pour développer leur créativité. Mais il y a une autre façon de jouer à Minecraft, c'est en utilisant une intelligence artificielle générée par GPT-3.

Dans cette présentation, nous allons parler un peu d'IA et de ML, de GPT-3 et de Codex, mais surtout, nous allons nous amuser à générer du code pour contrôler un bot dans Minecraft, le tout dans la bonne humeur ! Ca vous tente ?
--

==== Notes

TO BE COMPLETED

=== 20h00 - 20h50 : 10 ans déjà ! Devoxx France , l'envers du décors

==== Abstract

.Speakers : Arnaud Héritier, Nicolas Martignole, Antonio Goncalves, Zouheir Cadi
--
10 ans que Devoxx France accueille tous les ans plus de 2000 participants.
Comment en sommes nous arrivés là?
Comment se prépare un tel événement ?

De la sélection des sujets aux commandes de sodas, venez discuter avec l'équipe organisatrice pour tout savoir sur Devoxx France.
--

==== Notes

TO BE COMPLETED

=== 21h00 - 21h50 : Il y a des cloud en Europe ?

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/quentin_adam[Quentin Adam], https://cfp.devoxx.fr/2022/speaker/horacio_gonzalez[Horacio Gonzalez]
--
Si la domination sur le marché français des cloud américains est notable, de plus en plus de voix se retrouvent sur l'idée qu'il existe des alternatives européennes. De EUCLIDIA, à Hertzner, OVH, Clever Cloud, Scaleway, Orange... Nombre de solutions existent. Mais que leur manquent-t-elles ?

Le but du BoF est de retrouver les faiseurs de solutions et ceux qui sont intéressés à leur faire des feedbacks.
--

==== Notes

TO BE COMPLETED

=== -------------------- PROGRAMME TBD --------------------

== VENDREDI

=== 09h00 - 09h20 : Futurospective digitale : le futur est-il encore ce qu'il était ?

==== Abstract

.Speaker : https://cfp.devoxx.fr/2022/speaker/ludovic_cinquin[Ludovic Cinquin]
--
Les technologies digitales ont été un puissant moteur de transformation de notre civilisation, à tel point qu'elles se sont immiscées dans tous les recoins de nos vies et de notre planète.

Les 10 dernières années ont été ébouriffantes. Qu'en sera-t-il des 10 prochaines ?

Même si la prévision est un art difficile - surtout en ce qui concerne l'avenir -, nous pouvons identifier quelques macro-tendances qui structureront le futur de notre industrie. Le reste sera à écrire. Avec des lignes de code ?
--

==== Notes

TO BE COMPLETED

=== 09h50 - 10h10 : La quête d'une gouvernance collaborative du web

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/le_nguyen_hoang[Lê Nguyên Hoang]
--
Le web est de plus en plus attaqué par des campagnes de désinformation, qui emploient des usines de trolls pour manipuler l'opinion publique, noyer les informations compromettantes et amplifier la haine. Cette guerre de l'information est devenue un enjeu de sécurité nationale.

En réaction à cela, les géants du web ont pris des décisions radicales et unilatérales, comme le bannissement de Donald Trump ou l'autorisation des appels au meurtre de Poutine et des soldats russes.

Dans cette présentation, après avoir insisté sur l'ampleur du problème, je présenterai la plateforme Tournesol, qui propose une gouvernance collaborative et sécurisée de la recommandation de l'information.

J'essaierai de convaincre le public que la recherche et le développement de telles solutions sont critiques pour le futur de l'humanité.
--

==== Notes

TO BE COMPLETED

=== 10h45 - 11h30 : Développ(eur|euse) Senior avec 6 ans d’expérience, et après ?

==== Abstract

.Speakers : Hugo Lassiege et Dimitri BAELI
--
Le sujet récurrent dans l’IT : si on est senior avec 6 ans d’expérience, quelle est l’étape d’après ? Faut-il devenir manager pour progresser ? Dans cette session nous vous proposons de découvrir les rôles de Staff Engineer, Principal Engineer, Fellow, Distinguished et la notion d’impact qui accompagne ces rôles. Nous espérons vous faire réfléchir également à la notion de leadership dans vos métiers, vos équipes, vos produits et l’entreprise.
--

==== Notes

TO BE COMPLETED

=== 11h45 - 12h30 : À la découverte des Docker Dev Environments

==== Abstract

.Speakers : Guillaume Lours et Djordje Lukic
--
Imaginez-vous en plein travail sur une nouvelle fonctionnalité et vous devez absolument faire une revue de code d'un de vos collègues. Vous allez encore une fois mettre de côté votre code en cours, récupérer celui de votre collègue et qui sait peut-être modifier votre environnement local pour tester ses changements ?
Et si nous vous proposions une nouvelle expérience de développement ? Comment ? Et pourquoi pas par un simple Copier/Coller de l'url de votre repository GIT dans Docker Desktop ?

Les Dev Environments sont une manière d'isoler votre code, vos dépendances et processus en cours, vous permettant ainsi d'avoir plusieurs versions d'un même projet en test sur votre machine. Et bien plus encore, partagez simplement votre code avec les autres membres de votre équipe, interagissez via Docker Compose avec une stack applicative complexe ...
--

==== Notes

TO BE COMPLETED

=== 13h30 - 14h15 : Réception d'image satellite 🛰️ avec un Raspberry

==== Abstract

.Speakers : Guillaume Membré
--
Vous avez tous déjà vu les images météo satellites diffusées pendant la météo, mais est-ce que vous saviez que vous pouvez les capter directement du satellite ? Et en plus avec du matériel que vous avez peut être déjà ! Dans cette présentation, nous verrons comment réaliser une station de capture de flux radio émis par les satellites 🛰️ NOAA, en utilisant du matériel grand public comme un Raspberry, un tuner USB et pas mal de DIY 🛠️. Ce type de projet complétera sans problème une station météo à base de sondes de températures et d'Arduino.
--

==== Notes

TO BE COMPLETED

=== 14h30 - 15h15 : Mob programming, la véritable approche du développement en équipe

==== Abstract

.Speakers : Maxime Odye et Mathieu Pousse
--
Shérif, le manager, est en colère. Il vient de surprendre toute l’équipe de développement autour d’une même machine. Rendez-vous compte ! Après des comparaisons douteuses avec la DDE, il les a bien sermonnés et leur a ordonné de retourner à leur poste de travail immédiatement, un peu de sérieux ! Avec Shérif, la bamboche, c’est terminé !
Malheureusement, des Shérif, il en existe encore beaucoup dans les open-spaces de nos DSI. Partager un ordinateur entre plusieurs développeurs, mais pourquoi donc ?

Le MOB programming est une pratique s’appuyant sur le Lean et sur Extreme Programming qui consiste à réaliser une tâche, qu’elle soit technique ou non, à plusieurs. Les groomings, planifications et autres réunions de conception, ne serait-ce pas déjà des MOBs ?
De mythe à réalité, nous vous proposons de faire un retour d’expérience du MOB programming dans une équipe produit chez Ouest-France. Nous vous offrirons deux points de vue, celui du lead, présent depuis le début du projet (5 ans) et celui d’un développeur qui a rejoint l’équipe début 2021.
--

==== Notes

TO BE COMPLETED

=== 15h30 - 16h15 : CI/CD, le divorce serait-il prononcé ?

==== Abstract

.Speakers : Nicolas GIRAUD et Yann Schepens
--
A l'heure des digital factories, des transformations numériques, et autres mutations DevOps de nos organisations, les concepts du CI/CD sont poussés toujours plus loin...

A un moment où tout devient pipeline, où chaque action est automatisée, enchaînée et intégrée dans des scénarios, ne faisons-nous pas exploser la complexité de nos déploiements ? 
Comment faire pour maintenir cet écosystème qui doit nous aider à rester concentrés sur la valeur de nos produits ?

Et si, alors que nous tendons vers les "Everything As Code", des solutions se trouvaient déjà au cour de nos applications ? 
Et si nous, développeuses et développeurs logiciel, avions une partie de la réponse entre nos mains ?

A la lumière de leurs expériences et surtout enrichi par de nombreux échanges, Nicolas et Yann se proposent de démontrer en quoi certaines pratiques du développement moderne peuvent nous aider à limiter les risques.
Pour que maintenir vos pipelines reste un jeu d'enfant...
--

==== Notes

TO BE COMPLETED

=== 16h45 - 17h30 : Pourquoi DevOps ne tient pas ses promesses ?

==== Abstract

.Speaker : Gérôme Egron et Guillaume Mathieu
--
La plupart des clients que nous accompagnons disent faire du DevOps. Pourtant la réalité est loin de nous apporter satisfaction et les bénéfices attendus d'un point de vue théorique ne sont pas au rendez-vous.

Quelles sont les promesses de DevOps et pourquoi ne sont-elles pas tenues ? Est-ce que le monde des Devs est incompatible avec le monde des Ops ou est-ce que le problème est ailleurs ?

Nous allons partir des bases pour comprendre ce qu’il y a derrière le mot DevOps et partager nos expériences afin d'explorer les pratiques, bonnes ou mauvaises, rencontrées sur le terrain.

Après notre slot, vous aurez une compréhension claire du DevOps ainsi que des trucs et astuces pour amorcer cette transformation culturelle en évitant les pièges les plus communs.
--

==== Notes

TO BE COMPLETED

=== 17h45 - 18h30 (252AB) : Les Cast Codeurs en 🪑 et en 🦴

==== Abstract

.Speakers : https://cfp.devoxx.fr/2022/speaker/emmanuel_bernard[Emmanuel Bernard], https://cfp.devoxx.fr/2022/speaker/guillaume_laforge[Guillaume Laforge], https://cfp.devoxx.fr/2022/speaker/antonio_goncalves[Antonio Goncalves], https://cfp.devoxx.fr/2022/speaker/arnaud_heritier[Arnaud Héritier], https://cfp.devoxx.fr/2022/speaker/audrey_neveu[Audrey Neveu],
--
👻 Guillaume sort de ce titre ! 🤡

Les Cast Codeurs, le papy des podcasts de développement francophones revient cette année à Devoxx pour clôturer cette belle conférence dans la relaxation, la joie et peut être la blague carambar. Venez partager avec le public vos impressions de cette cuvée Devoxx, des choses qui vous on surpris, des tendances qui se dessinent.
--

==== Notes

TO BE COMPLETED

